# Travis configuration
language: python

# whitelist
branches:
    only:
        - master

# enable docker
services:
    - docker

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update -qq
    - docker version

install:
    - pip install pip --upgrade
    - pip install click pyaml Jinja2 pykwalify tox tox-travis coveralls
    - which python
    - python -V
    - pip -V

script:
    - ./unittests.sh
    - tox

after_success:
    - coveralls

notifications:
    email:
        recipients:
           - thomas.lehmann.private@gmail.com
        on_success: always
        on_failure: always
