matrix:
  - name: one
    env:
        mode: one
  - name: two
    env:
        mode: two

hooks:
    cleanup: 
        script: |
            echo "cleanup has been called"

pipeline:
  - env:
      foo: foo at pipeline level
      bar: bar at pipeline level

  - stage(build):
    - env:
        foo: foo at stage level
        bar: bar at stage level

    - tasks:
      - env:
          foo: foo at task group level
          bar: bar at task group level

      - shell:
            script: echo "hello world! (mode=$mode)"
            tags:
                - demo
      - shell:
            script: |
                echo "foo=$foo"
                echo "bar=$bar"
