matrix:
  - mode: one
  - mode: two

pipeline:
  - env:
      foo: foo at pipeline level
      bar: bar at pipeline level

  - stage(build):
    - env:
        foo: foo at stage level
        bar: bar at stage level

    - tasks:
      - env:
          foo: foo at task group level
          bar: bar at task group level

      - shell: echo "hello world! (mode=$mode)"
      - shell: |
          echo "foo=$foo"
          echo "bar=$bar"
