schema;env_map:
  type: map
  mapping:
    env:
      type: map
      matching-rule: all
      mapping:
        regex;(.+):
            type: str

type: map
mapping:

  matrix:
    type: seq
    sequence:
      - type: map
        mapping:
          name:
            type: str
          env:
            type: map
            matching-rule: all
            mapping:
              regex;(.+):
                  type: str

  pipeline:
    required: yes
    type: seq
    sequence:
      - include: env_map
      - type: map
        mapping:
          regex;(stage\(.+\)):
            type: seq
            sequence:
              - include: env_map
              - type: map
                mapping:
                  tasks:
                    type: seq
                    sequence:
                      - include: env_map
                      - type: map
                        mapping:
                          shell:
                            type: str
