matrix:
  - name: Python 3.6
    env: {PYTHON_VERSION: py36, TAG: "3.6"}
    tags: ['py36']
  - name: Python 3.7
    env: {PYTHON_VERSION: py37, TAG: "3.7"}
    tags: ['py37']

model:
  templates:
    dockerfiles:
      py36: |
        FROM centos:7
        RUN yum -y install yum-utils git
        RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
        RUN yum -y install python36u python36u-pip
        RUN pip3.6 install tox

      py37: |
        FROM centos:7
        RUN yum -y install wget gcc make openssl-devel libffi-devel git
        RUN wget -q https://www.python.org/ftp/python/3.7.0/Python-3.7.0a2.tar.xz
        RUN tar -xf $(ls Python*.tar.xz)
        RUN cd Python*;./configure;make && make altinstall
        RUN ln -s /usr/local/bin/pip3.7 /usr/local/bin/pip
        RUN pip install pip --upgrade
        RUN pip install setuptools --upgrade
        RUN pip install tox

pipeline:
  - stage(Example):
    - tasks:
      - docker(image):
          name: python
          tag: "{{ env.TAG }}"
          unique: no
          script: "{{ model.templates.dockerfiles[env.PYTHON_VERSION] }}"
