model:
    image: centos:7

pipeline:
    - stage(Example):
        - tasks(ordered):
            - packer:
                script: |
                  {
                    "builders": [{
                        "type": "docker",
                        "image": "{{ model.image }}",
                        "commit": true,
                        "changes": [
                            "LABEL pipeline={{ env.PIPELINE_PID }}",
                            "LABEL pipeline-stage={{ env.PIPELINE_STAGE }}"
                        ]
                    }],

                    "provisioners": [{
                        "type": "shell",
                        "inline": [
                            "yum -y install bc"
                        ]
                    }, {
                        "type": "file",
                        "source": "examples/primes.sh",
                        "destination": "/root/primes.sh"
                    }],

                    "post-processors": [{
                        "type": "docker-tag",
                        "repository": "spline/packer/demo",
                        "tag": "0.1"
                    }]
                  }
