model:
  max-number: 100

pipeline:
    - stage(Calculate Primes):
        - tasks(ordered):
            - shell:
                script: |
                  function is_prime() {
                      n=$1
                      if [ "${n}" -lt 2 ]; then return; fi
                      if [ "$(expr $n % 2)" -eq 0 ]; then
                          if [ "${n}" == "2" ]; then echo "yes"; fi
                          return;
                      fi
                      d=$(echo "sqrt(${n})"|bc)
                      for k in $(seq 3 2 ${d}); do
                          if [ "$(expr $n % $k)" -eq 0 ]; then return; fi
                      done
                      echo "yes"
                  }

                  for n in $(seq 0 {{ model['max-number'] }}); do
                      if [ "$(is_prime ${n})" == "yes" ]; then
                          echo -n "${n} ";
                      fi
                  done
                tags:
                  - embedded

            - shell:
                script: examples/primes.sh {{ model['max-number'] }}
                tags:
                  - file
