model:
   data:
     - hello
     - world

pipeline:
    - stage(Example):
        - tasks(ordered):
            - shell:
                script: echo "shell - {{ item }}"
                with:
                    - hello
                    - world

            - docker(container):
                script: echo "docker - {{ item }}"
                with:
                    - hello
                    - world

            - shell:
                script: echo "rendered with - {{ item }}"
                with: "{{ model.data }}"

        - tasks(parallel):
            - shell:
                script: |
                    echo "{{ item.message }}: start"
                    sleep {{ item.time }}
                    echo "{{ item.message }}: done"
                with:
                    - message: first
                      time: 3
                    - message: second
                      time: 2
                    - message: third
                      time: 1
