schema;env_map:
  type: map
  mapping:
    env:
      type: map
      matching-rule: all
      mapping:
        regex;(.+):
            type: str

type: map
mapping:
  regex;((matrix\(parallel\)|matrix\(ordered\)|matrix)$):
    type: seq
    sequence:
      - type: map
        mapping:
          name:
            type: str
          env:
            type: map
            matching-rule: all
            mapping:
              regex;(.+):
                  type: str
          tags:
            type: seq
            sequence:
              - type: str

  hooks:
    type: map
    mapping:
      cleanup:
        type: map
        mapping:
          script: { type: str }

  model:
    type: map
    mapping:
      regex;([a-z][a-z]*):
        type: any

  pipeline:
    required: yes
    type: seq
    sequence:
      - include: env_map
      - type: map
        mapping:
          regex;(stage\(.+\)):
            type: seq
            sequence:
              - include: env_map
              - type: map
                mapping:
                  regex;((tasks\(parallel\)|tasks\(ordered\)|tasks)$):
                    type: seq
                    sequence:
                      - include: env_map
                      - type: map
                        mapping:
                          shell:
                            type: map
                            mapping:
                              title:  { type: str }
                              script: { type: str, required: yes }
                              tags:
                                type: seq
                                sequence:
                                  - type: str
                      - type: map
                        mapping:
                          docker(container):
                            type: map
                            mapping:
                              title:  { type: str }
                              image:  { type: str }
                              remove: { type: bool, enum: [true, false], default: true }
                              background: { type: bool, enum: [true, false], default: false }
                              mount: { type: bool, enum: [true, false], default: false }
                              script: { type: str, required: yes }
                              tags:
                                type: seq
                                sequence:
                                  - type: str
