#!/usr/bin/env python
from unittest import TestLoader, TextTestRunner
from random import randint

# TODO: using main
# TODO: using click
# TODO: using seed for random for reproducing things

TestLoader.sortTestMethodsUsing = lambda _, a, b: randint(-1, 1)

loader = TestLoader()
suite = loader.discover(start_dir='tests')

runner = TextTestRunner(verbosity=2)
runner.run(suite)
